language: node_js
node_js:
- 4.6.2
- 6.9.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_ae225686951e_key -iv $encrypted_ae225686951e_iv
  -in privatekey.pem.enc -out ~\/keys/xero/privatekey.pem -d
